language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
cache:
  directories:
  - "~/.m2/repository"
env:
  global:
  - secure: OsrubYh4sPpKAYBNGtB47t48/vGFrrsuVKnKYP8uD4MkdyEP3JWRKK+gePFhSsUEidZbuaRNaqVL+qVlzMgZEsFiwnfTIl2tqf9dVjS/blDpTwjrN7GL8GwndZsWB1r5FDiCDU9/Y7zaT+1wrnR5OwTr8hVWnc5wp4VVa53dPTM=
  - secure: H8NOTdAllYHarShpdo8qx74Bs4cQb3YvCXNWxiNilTXMyXZUWpmUiffb6WyhM8SKXtfc+/z07yZ8NXiwhALIBp3XKj2XZbr5cT/0MM6BCWzTBd6l07jyvCHeOe+13rmHWEIPQ9Te23uuqiZWhDegKaSghkcOgz3XyKKW4RnnHvI=
  - secure: OZofamvBMoU7fUhT2KfIJPKOBl3jaUgxpQoi4IIEYJ5FjlXG4Pdj//L7xISeFBubE1ApRbuM/kGxJtl/u2UWgvw3wblHRwJd5ZtPQOl+y1dbU6B+ldIuyaAIiPpGQGt1zzsomhvnfwQ9QMDbSfXBOc/JCshCm+IsuZyOU1JeXzc=
  - secure: YCMnpFy62lxGu75Gr0JJzZLl8BbDj2It36yhw1ej61BBqiSv8g3TShSmBXD9j5PVIufAdFRCSGgrAugV39CK/qt4WwrB53zhmtGSCVWvL9qKOJy9lDG1A9zz+JRSvmxin/VzkZRniVp2m1uwDj+hW4iAKT+YqoniTjUw+ZIfTg8=
