//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.07 at 06:54:45 PM CET 
//


package de.unihalle.informatik.rhizoTrak.config;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="statusList"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="status" maxOccurs="unbounded"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="fullName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="abbreviation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                             &lt;element name="red" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                             &lt;element name="green" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                             &lt;element name="blue" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                             &lt;element name="alpha" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *                             &lt;element name="selectable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statusList"
})
@XmlRootElement(name = "config")
public class Config {

    @XmlElement(required = true)
    protected Config.StatusList statusList;

    /**
     * Gets the value of the statusList property.
     * 
     * @return
     *     possible object is
     *     {@link Config.StatusList }
     *     
     */
    public Config.StatusList getStatusList() {
        return statusList;
    }

    /**
     * Sets the value of the statusList property.
     * 
     * @param value
     *     allowed object is
     *     {@link Config.StatusList }
     *     
     */
    public void setStatusList(Config.StatusList value) {
        this.statusList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="status" maxOccurs="unbounded"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="fullName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="abbreviation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                   &lt;element name="red" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *                   &lt;element name="green" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *                   &lt;element name="blue" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *                   &lt;element name="alpha" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
     *                   &lt;element name="selectable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status"
    })
    public static class StatusList {

        @XmlElement(required = true)
        protected List<Config.StatusList.Status> status;

        /**
         * Gets the value of the status property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the status property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStatus().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Config.StatusList.Status }
         * 
         * 
         */
        public List<Config.StatusList.Status> getStatus() {
            if (status == null) {
                status = new ArrayList<Config.StatusList.Status>();
            }
            return this.status;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="fullName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="abbreviation" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *         &lt;element name="red" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
         *         &lt;element name="green" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
         *         &lt;element name="blue" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
         *         &lt;element name="alpha" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
         *         &lt;element name="selectable" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "fullName",
            "abbreviation",
            "red",
            "green",
            "blue",
            "alpha",
            "selectable"
        })
        public static class Status {

            @XmlElement(required = true)
            protected String fullName;
            @XmlElement(required = true)
            protected String abbreviation;
            @XmlElement(required = true)
            protected BigInteger red;
            @XmlElement(required = true)
            protected BigInteger green;
            @XmlElement(required = true)
            protected BigInteger blue;
            @XmlElement(required = true)
            protected BigInteger alpha;
            protected boolean selectable;

            /**
             * Gets the value of the fullName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFullName() {
                return fullName;
            }

            /**
             * Sets the value of the fullName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFullName(String value) {
                this.fullName = value;
            }

            /**
             * Gets the value of the abbreviation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAbbreviation() {
                return abbreviation;
            }

            /**
             * Sets the value of the abbreviation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAbbreviation(String value) {
                this.abbreviation = value;
            }

            /**
             * Gets the value of the red property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getRed() {
                return red;
            }

            /**
             * Sets the value of the red property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setRed(BigInteger value) {
                this.red = value;
            }

            /**
             * Gets the value of the green property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getGreen() {
                return green;
            }

            /**
             * Sets the value of the green property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setGreen(BigInteger value) {
                this.green = value;
            }

            /**
             * Gets the value of the blue property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getBlue() {
                return blue;
            }

            /**
             * Sets the value of the blue property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setBlue(BigInteger value) {
                this.blue = value;
            }

            /**
             * Gets the value of the alpha property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getAlpha() {
                return alpha;
            }

            /**
             * Sets the value of the alpha property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setAlpha(BigInteger value) {
                this.alpha = value;
            }

            /**
             * Gets the value of the selectable property.
             * 
             */
            public boolean isSelectable() {
                return selectable;
            }

            /**
             * Sets the value of the selectable property.
             * 
             */
            public void setSelectable(boolean value) {
                this.selectable = value;
            }

        }

    }

}
